### ISSUE TITLE
bug issue 

### ISSUE THREAD

**Issue by waseem-terafort** [ogzkesk/EonAd#1]
show rewarded and show rewarded2 click not working its show loading and come back

**Comment by waseem-terafort** [comment]
when i click like again and again then in 3rd time ads come 
by the way nice work

**Comment by ogzkesk** [comment]
Thank you for feedback .
Only i realized not returning rewards problem after first show .
I fixed that. Now you can use **v1.0.8** version .
There is no problem with opening when clicks .
Might be problem on your emulator can you debug on real device and check results ?

**Comment by waseem-terafort** [comment]
yes it works now thanks
